### ISSUE TITLE
Private API keys shouldn't be pushed on a public GitHub repo.

### ISSUE THREAD

**Issue by Loukass23** [ZsuzsaMano/Rick_and_Morty#2]
https://github.com/ZsuzsaMano/Rick_and_Morty/blob/48dd5f2e9abe0541439a2ecbbaf4b1fef56c1d81/main.js#L1

**Comment by ZsuzsaMano** [comment]
Ups, and that wasnt even from this api :). MIssed it when cleaning up. Thx.
