### ISSUE TITLE
Add arrow to accordion on homepage

### ISSUE THREAD

**Issue by ZsuzsaMano** [ZsuzsaMano/Rick_and_Morty#9]

**Comment by stonespheres** [comment]
I can start this!
What sort of functionality are you looking for? Do you want the arrow for each element of the accordion?

**Comment by ZsuzsaMano** [comment]
I would need the arrows to point downwards, signaling, that it can be opened, and if open show up. Some animation on transition would be great. 

Thank you

**Comment by ZsuzsaMano** [comment]
![arrow](https://user-images.githubusercontent.com/51864343/101748913-690b7f80-3acd-11eb-934b-c3a35c00c73d.png)

**Comment by stonespheres** [comment]
Pull request created. #12 
I'll be updating the code later today to refine the positioning of the arrows.
![Screenshot_20201211_092622](https://user-images.githubusercontent.com/44436822/101849658-1bf1e100-3b93-11eb-8d31-947cb5b79eb9.png)
![Screenshot_20201211_092636](https://user-images.githubusercontent.com/44436822/101849660-1d230e00-3b93-11eb-9e0e-f1bd1db5d0b0.png)
